import 'package:flutter/material.dart';

const String PATH_IMG = 'assets/img/';
const String ICON_AIRPLANE = PATH_IMG + 'airplane.png';
const String ICON_BACKPACK = PATH_IMG + 'backpack.png';
const String ICON_CLIMATE = PATH_IMG + 'climate.png';
const String ICON_LIST = PATH_IMG + 'list.png';
const String ICON_USER = PATH_IMG + 'user.png';
const String ICON_ACOUNT = PATH_IMG + 'acount.png';
const String ICON_CALIFICA = PATH_IMG + 'califica.png';
const String ICON_EDIT = PATH_IMG + 'edit.png';
const String ICON_IDIOMA = PATH_IMG + 'idioma.png';
const String ICON_SOPORTE = PATH_IMG + 'soporte.png';
const String ICON_VERSION = PATH_IMG + 'version.png';
const double kDefaultPadding = 20.0;
const double kPaddingInput = 40.0;
const kPrimaryColor = Colors.white;
const kBackgroundColor = Colors.white;
const kTextColor = Color(0xFF3C4046);
const kCursorColor = Colors.blue;
const kColorBorderSide = Color(0xFF868484);
const kColorPlaceHolder = Color(0xFFf4f4f4);
const kColorTextButton = Color(0xFF28c18d);
const kColorButtonLogin = Color(0xFFd1fae5);
const inputTextRadius = 15.0;
const buttonRadius = 20.0;
